### ISSUE TITLE
OSS Dependency Tracking ...

### ISSUE THREAD

**Issue by jeremy-donson** [acim/update-tools#4]
### The following regards all open source code updates across all environments.

- First, a list of all **standard core dependencies** + their tested configurations would set the foundation.
  - That dependency tree ought to be explicit?  Might that dep tree be defined in a yaml file?
  - Notification of code being updated (dev and stable releases) would be helpful . <nods>
  - What open source dependency tracking tools exist?
  - How ought we be notified of updates?

- Next, a means to locally install and test the updates would bear confidence prior to leaning on them.
  - How to escalate that testing to central QA environment?
  - How to handle multiple current versions installed?  Likely in virtual envs?
  - Updates make this even more challenging.  Rules of testing legacy, current and emerging code are needed.

- Then,
allowing tested newer versions to supersede in a given **namespace** shall not prevent us from rolling back to earlier tools.
  - We may want legacy, current and emerging tools available in parallel.  We may want to decommission legacy code.
  - This can vary widely per namespace.

- Finally, we have a solid foundation for improving our testing tools, methods and techniques.
  - Properly reporting evolving test results back to tool repo maintainers will improve tool chain quality.
  - Registries of tested tools will pave the paths of least resistance.

- Each actively maintained open source github project needs proper testing before being added to a core dep registry.

**Comment by acim** [comment]
What this has to do with me or this small project?
